Updated readme to include project and branch description
quipper/apollo-frontpage-android-app pull request #7
Opened 2020-04-27 01:58 UTC by padobariya

Updated readme to include project and branch description

2020-04-28 04:13 UTC, aruke requested changes
I added some comments.

2020-04-28 04:13 UTC, aruke commented on README.md
> +We followed following workflow while working GraphQL endpoint and the Apollo SDK.
```suggestion
We followed the following workflow while working GraphQL endpoint and the Apollo SDK.

```

2020-04-28 04:13 UTC, aruke commented on README.md
> +master | The master branch contains the GraphQL implementation using RxJava2 support  |
Basically every branch is going to have GraphQL implementation so better to skip that part.
Just add `RxJava2 Support`.
For other branches, we can add a short description like above.

2020-04-28 04:48 UTC, padobariya commented
@aruke Thanks! Addressed 👍

2020-04-28 05:00 UTC, aruke approved these changes
Looks good now!

2020-05-07 05:49 UTC, oh-naoki approved these changes
⭐ LGTM ⭐

2020-05-11 02:37 UTC, merged